### ISSUE TITLE
1. In Preliminary Selection page, Status combo have 2 values e.g. Preliminary Selected, Pending

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/capacity#1]
-New application will have default "Applied" status.
-In status combo user will get 2 values "Preliminary Selected" and "Pending"
-If user select "Preliminary Selected" it will remove from the list and appeared in "Final Selection" page.
-If user select "Pending" then it will remain in the list as a pending status
![image](https://user-images.githubusercontent.com/52271735/60246468-8a2fde80-98e0-11e9-8f55-b52d4ea90710.png)

**Comment by udaykumarmca** [comment]
Finished
