### ISSUE TITLE
2. In Final Selection page, Status combo have 4 values e.g. "Approved", "Waiting", "Re-check", "Not Approved"

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/capacity#2]
- When application come in "Final Selection" list then default status will be "Preliminary Selected"
-If user select "Approved" then it will appeared in Applicant List of GO Creation Page
-If user select "Waiting" then it will remain in the Final Selection List and status will be change to "Waiting"
-If user select "Re-Check" then it will appeared in Preliminary list and status will be change to "Pending"
-If user select "Not Approved" then it will remain in the Final Selection List and status will be change to "Not Approved"
![image](https://user-images.githubusercontent.com/52271735/60247214-11318680-98e2-11e9-8853-7fd37e442081.png)

**Comment by udaykumarmca** [comment]
Finished
