### ISSUE TITLE
31. Certificate Upload-> There should be a List page for view and download the uploaded certificate.

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/capacity#31]

**Comment by udaykumarmca** [comment]
Finished

**Comment by collecteddoc** [comment]
After upload, an uploaded certificate could not able to download. there is no such feature present there in the UI. Also in "applied courselist" Combobox there should have those courses for which applicant get the approval, not all the courses.

**Comment by udaykumarmca** [comment]
we need a call to explain this. That it cant be fixed
