### ISSUE TITLE
34. Master/PGD Application->Education-> Need new column for 'Certificate/Attachment Upload'

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/capacity#34]
![image](https://user-images.githubusercontent.com/52271735/60388531-d2175700-9ad4-11e9-8e60-46d9808a51ec.png)

**Comment by udaykumarmca** [comment]
Finished

**Comment by collecteddoc** [comment]
please share the Master/PGD Application->Education->url is missing

**Comment by udaykumarmca** [comment]
Finished
